CREATE OR REPLACE TABLE customers (
customer_id INT,
first_name STRING,
last_name STRING,
gender STRING,
date_of_birth DATE,
age INT,
marital_status STRING,
household_income INT,
occupation STRING,
education_level STRING,
city STRING,
state STRING,
pincode STRING,
country STRING,
latitude FLOAT,
longitude FLOAT,
signup_date DATE,
last_login_date DATE,
customer_tenure_days INT,
customer_type STRING,
loyalty_tier STRING,
loyalty_points INT,
preferred_language STRING,
preferred_device STRING,
preferred_payment_method STRING,
avg_session_duration FLOAT,
sessions_last_30_days INT,
weekend_shopper_flag BOOLEAN,
night_shopper_flag BOOLEAN,
preferred_category STRING,
secondary_category STRING,
brand_affinity_score FLOAT,
email STRING,
phone_number STRING,
whatsapp_opt_in BOOLEAN,
email_opt_in BOOLEAN,
discount_sensitivity_score FLOAT,
price_sensitivity_score FLOAT,
return_behavior_score FLOAT,
fraud_risk_score FLOAT,
last_order_date DATE,
last_order_value FLOAT,
customer_lifetime_value FLOAT,
total_orders INT,
referral_source STRING,
campaign_source STRING,
device_os STRING,
app_version STRING,
churn_risk_score FLOAT,
engagement_score FLOAT
); --present in snowflake lerning db > customers


--auto-make table
INSERT INTO customers
SELECT
    ROW_NUMBER() OVER (ORDER BY SEQ4()) AS customer_id,
    ARRAY_CONSTRUCT('Aarav','Vivaan','Aditya','Vihaan','Arjun','Sai','Reyansh','Ayaan','Krishna','Ishaan','Ananya','Diya','Saanvi','Aanya','Aadhya','Priya','Kavya','Meera','Riya','Shreya')[UNIFORM(0,19,RANDOM())]::STRING AS first_name,
    ARRAY_CONSTRUCT('Sharma','Patel','Singh','Kumar','Gupta','Reddy','Nair','Menon','Verma','Joshi','Iyer','Rao','Desai','Mehta','Shah','Pillai','Chopra','Malhotra','Banerjee','Mukherjee')[UNIFORM(0,19,RANDOM())]::STRING AS last_name,
    ARRAY_CONSTRUCT('male','female','other')[UNIFORM(0,2,RANDOM())]::STRING AS gender,
    DATEADD(DAY, -UNIFORM(6570, 25550, RANDOM()), CURRENT_DATE()) AS date_of_birth,
    UNIFORM(18, 70, RANDOM()) AS age,
    ARRAY_CONSTRUCT('single','married','divorced','widowed')[UNIFORM(0,3,RANDOM())]::STRING AS marital_status,
    UNIFORM(200000, 5000000, RANDOM()) AS household_income,
    ARRAY_CONSTRUCT('Engineer','Doctor','Teacher','Business Owner','Manager','Analyst','Designer','Developer','Consultant','Student','Retired','Homemaker')[UNIFORM(0,11,RANDOM())]::STRING AS occupation,
    ARRAY_CONSTRUCT('High School','Bachelor','Master','PhD','Diploma')[UNIFORM(0,4,RANDOM())]::STRING AS education_level,
    ARRAY_CONSTRUCT('Mumbai','Delhi','Bangalore','Hyderabad','Chennai','Kolkata','Pune','Ahmedabad','Jaipur','Lucknow','Surat','Kanpur','Nagpur','Indore','Thane','Bhopal','Visakhapatnam','Patna','Vadodara','Coimbatore')[UNIFORM(0,19,RANDOM())]::STRING AS city,
    ARRAY_CONSTRUCT('Maharashtra','Delhi','Karnataka','Telangana','Tamil Nadu','West Bengal','Gujarat','Rajasthan','Uttar Pradesh','Madhya Pradesh')[UNIFORM(0,9,RANDOM())]::STRING AS state,
    LPAD(UNIFORM(100000, 999999, RANDOM())::STRING, 6, '0') AS pincode,
    'India' AS country,
    UNIFORM(8.0, 35.0, RANDOM())::FLOAT AS latitude,
    UNIFORM(68.0, 97.0, RANDOM())::FLOAT AS longitude,
    DATEADD(DAY, -UNIFORM(30, 1825, RANDOM()), CURRENT_DATE()) AS signup_date,
    DATEADD(DAY, -UNIFORM(0, 30, RANDOM()), CURRENT_DATE()) AS last_login_date,
    UNIFORM(30, 1825, RANDOM()) AS customer_tenure_days,
    ARRAY_CONSTRUCT('new','returning','loyal')[UNIFORM(0,2,RANDOM())]::STRING AS customer_type,
    ARRAY_CONSTRUCT('bronze','silver','gold','platinum')[UNIFORM(0,3,RANDOM())]::STRING AS loyalty_tier,
    UNIFORM(0, 50000, RANDOM()) AS loyalty_points,
    ARRAY_CONSTRUCT('English','Hindi','Tamil','Telugu','Marathi','Bengali','Gujarati','Kannada')[UNIFORM(0,7,RANDOM())]::STRING AS preferred_language,
    ARRAY_CONSTRUCT('mobile','web','app')[UNIFORM(0,2,RANDOM())]::STRING AS preferred_device,
    ARRAY_CONSTRUCT('COD','UPI','card','wallet')[UNIFORM(0,3,RANDOM())]::STRING AS preferred_payment_method,
    ROUND(UNIFORM(1.0, 30.0, RANDOM()), 2)::FLOAT AS avg_session_duration,
    UNIFORM(1, 50, RANDOM()) AS sessions_last_30_days,
    UNIFORM(0, 1, RANDOM())::BOOLEAN AS weekend_shopper_flag,
    UNIFORM(0, 1, RANDOM())::BOOLEAN AS night_shopper_flag,
    ARRAY_CONSTRUCT('Electronics','Fashion','Home & Kitchen','Beauty','Sports','Books','Grocery','Toys','Health','Automotive')[UNIFORM(0,9,RANDOM())]::STRING AS preferred_category,
    ARRAY_CONSTRUCT('Electronics','Fashion','Home & Kitchen','Beauty','Sports','Books','Grocery','Toys','Health','Automotive')[UNIFORM(0,9,RANDOM())]::STRING AS secondary_category,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS brand_affinity_score,
    LOWER(first_name) || '.' || LOWER(last_name) || UNIFORM(1,999,RANDOM())::STRING || '@' || ARRAY_CONSTRUCT('gmail.com','yahoo.com','outlook.com','hotmail.com')[UNIFORM(0,3,RANDOM())]::STRING AS email,
    '+91' || UNIFORM(6000000000, 9999999999, RANDOM())::STRING AS phone_number,
    UNIFORM(0, 1, RANDOM())::BOOLEAN AS whatsapp_opt_in,
    UNIFORM(0, 1, RANDOM())::BOOLEAN AS email_opt_in,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS discount_sensitivity_score,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS price_sensitivity_score,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS return_behavior_score,
    ROUND(UNIFORM(0.0, 0.5, RANDOM()), 2)::FLOAT AS fraud_risk_score,
    DATEADD(DAY, -UNIFORM(0, 90, RANDOM()), CURRENT_DATE()) AS last_order_date,
    ROUND(UNIFORM(100.0, 50000.0, RANDOM()), 2)::FLOAT AS last_order_value,
    ROUND(UNIFORM(1000.0, 500000.0, RANDOM()), 2)::FLOAT AS customer_lifetime_value,
    UNIFORM(1, 200, RANDOM()) AS total_orders,
    ARRAY_CONSTRUCT('organic','ads','influencer','direct')[UNIFORM(0,3,RANDOM())]::STRING AS referral_source,
    ARRAY_CONSTRUCT('summer_sale','diwali_offer','new_year','flash_sale','referral_bonus','first_purchase',NULL)[UNIFORM(0,6,RANDOM())]::STRING AS campaign_source,
    ARRAY_CONSTRUCT('android','ios','windows')[UNIFORM(0,2,RANDOM())]::STRING AS device_os,
    'v' || UNIFORM(1,5,RANDOM())::STRING || '.' || UNIFORM(0,9,RANDOM())::STRING || '.' || UNIFORM(0,9,RANDOM())::STRING AS app_version,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS churn_risk_score,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS engagement_score
FROM TABLE(GENERATOR(ROWCOUNT => 3000));


select top 10 * from customers;

---------------------------------orders--------------------

CREATE OR REPLACE TABLE orders (
order_id INT,
customer_id INT,
order_date DATE,
order_time STRING,
product_id STRING,
product_name STRING,
brand STRING,
category STRING,
sub_category STRING,
quantity INT,
unit_price FLOAT,
order_value FLOAT,
discount_amount FLOAT,
coupon_code STRING,
payment_type STRING,
payment_status STRING,
order_status STRING,
delivery_partner STRING,
warehouse_id STRING,
shipping_city STRING,
shipping_state STRING,
shipping_pincode STRING,
delivery_time_days INT,
is_returned BOOLEAN,
return_reason STRING,
refund_amount FLOAT,
is_cancelled BOOLEAN,
cancellation_reason STRING,
cod_flag BOOLEAN,
customer_rating INT,
inventory_available_flag BOOLEAN,
stock_level_at_order INT,
high_rto_risk_flag BOOLEAN,
fraud_flag BOOLEAN,
order_source STRING,
traffic_source STRING,
campaign_id STRING,
margin FLOAT,
profit FLOAT
);


INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.orders
WITH base_data AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY SEQ4()) AS order_id,
        UNIFORM(1, 3000, RANDOM()) AS customer_id,
        DATEADD(DAY, -UNIFORM(0, 365, RANDOM()), CURRENT_DATE()) AS order_date,
        LPAD(UNIFORM(0,23,RANDOM())::STRING,2,'0') || ':' || LPAD(UNIFORM(0,59,RANDOM())::STRING,2,'0') || ':' || LPAD(UNIFORM(0,59,RANDOM())::STRING,2,'0') AS order_time,
        'PRD' || LPAD(UNIFORM(1,5000,RANDOM())::STRING,5,'0') AS product_id,
        ARRAY_CONSTRUCT('Wireless Earbuds','Smart Watch','Running Shoes','Cotton T-Shirt','Laptop Stand','Phone Case','Backpack','Water Bottle','Yoga Mat','Bluetooth Speaker','LED Bulb','Kitchen Knife Set','Face Cream','Hair Dryer','Gaming Mouse','Desk Lamp','Sunglasses','Wallet','Perfume','Book')[UNIFORM(0,19,RANDOM())]::STRING AS product_name,
        ARRAY_CONSTRUCT('Samsung','Apple','Nike','Adidas','Boat','OnePlus','Puma','Philips','Sony','LG','Bajaj','Prestige','Lakme','Dyson','Logitech','HP','Ray-Ban','Wildcraft','Forest Essentials','Penguin')[UNIFORM(0,19,RANDOM())]::STRING AS brand,
        ARRAY_CONSTRUCT('Electronics','Fashion','Home & Kitchen','Beauty','Sports','Books','Grocery','Toys','Health','Automotive')[UNIFORM(0,9,RANDOM())]::STRING AS category,
        ARRAY_CONSTRUCT('Audio','Wearables','Footwear','Clothing','Accessories','Storage','Fitness','Skincare','Haircare','Gaming')[UNIFORM(0,9,RANDOM())]::STRING AS sub_category,
        UNIFORM(1, 5, RANDOM()) AS quantity,
        ROUND(UNIFORM(100.0, 15000.0, RANDOM()), 2)::FLOAT AS unit_price,
        UNIFORM(0, 100, RANDOM()) AS rnd_payment,
        UNIFORM(0, 100, RANDOM()) AS rnd_cancel,
        UNIFORM(0, 100, RANDOM()) AS rnd_return,
        UNIFORM(0, 100, RANDOM()) AS rnd_fraud
    FROM TABLE(GENERATOR(ROWCOUNT => 5000))
)
SELECT
    order_id,
    customer_id,
    order_date,
    order_time,
    product_id,
    product_name,
    brand,
    category,
    sub_category,
    quantity,
    unit_price,
    ROUND(quantity * unit_price, 2)::FLOAT AS order_value,
    ROUND(quantity * unit_price * UNIFORM(0.0, 0.3, RANDOM()), 2)::FLOAT AS discount_amount,
    CASE WHEN UNIFORM(0,100,RANDOM()) < 40 THEN ARRAY_CONSTRUCT('SAVE10','FLAT20','FIRST50','DIWALI25','SUMMER15','NEWUSER')[UNIFORM(0,5,RANDOM())]::STRING ELSE NULL END AS coupon_code,
    CASE WHEN rnd_payment < 35 THEN 'COD' WHEN rnd_payment < 60 THEN 'UPI' WHEN rnd_payment < 80 THEN 'Card' ELSE 'Wallet' END AS payment_type,
    CASE WHEN rnd_cancel < 8 THEN 'failed' WHEN rnd_cancel < 12 THEN 'pending' ELSE 'completed' END AS payment_status,
    CASE 
        WHEN rnd_cancel < 10 THEN 'cancelled'
        WHEN rnd_return < 15 THEN 'returned'
        WHEN UNIFORM(0,100,RANDOM()) < 85 THEN 'delivered'
        ELSE 'shipped'
    END AS order_status,
    ARRAY_CONSTRUCT('Delhivery','BlueDart','Ekart','DTDC','Shadowfax','Ecom Express','XpressBees')[UNIFORM(0,6,RANDOM())]::STRING AS delivery_partner,
    'WH' || LPAD(UNIFORM(1,20,RANDOM())::STRING,3,'0') AS warehouse_id,
    ARRAY_CONSTRUCT('Mumbai','Delhi','Bangalore','Hyderabad','Chennai','Kolkata','Pune','Ahmedabad','Jaipur','Lucknow')[UNIFORM(0,9,RANDOM())]::STRING AS shipping_city,
    ARRAY_CONSTRUCT('Maharashtra','Delhi','Karnataka','Telangana','Tamil Nadu','West Bengal','Gujarat','Rajasthan','Uttar Pradesh','Madhya Pradesh')[UNIFORM(0,9,RANDOM())]::STRING AS shipping_state,
    LPAD(UNIFORM(100000, 999999, RANDOM())::STRING, 6, '0') AS shipping_pincode,
    UNIFORM(1, 10, RANDOM()) AS delivery_time_days,
    rnd_return < 15 AS is_returned,
    CASE WHEN rnd_return < 15 THEN ARRAY_CONSTRUCT('Defective product','Wrong item','Size issue','Changed mind','Better price elsewhere','Late delivery')[UNIFORM(0,5,RANDOM())]::STRING ELSE NULL END AS return_reason,
    CASE WHEN rnd_return < 15 THEN ROUND(quantity * unit_price * 0.9, 2)::FLOAT ELSE 0 END AS refund_amount,
    rnd_cancel < 10 AS is_cancelled,
    CASE WHEN rnd_cancel < 10 THEN ARRAY_CONSTRUCT('Changed mind','Found cheaper','Delivery too slow','Payment issue','Ordered by mistake')[UNIFORM(0,4,RANDOM())]::STRING ELSE NULL END AS cancellation_reason,
    rnd_payment < 35 AS cod_flag,
    CASE WHEN rnd_cancel >= 10 AND rnd_return >= 15 THEN UNIFORM(1, 5, RANDOM()) ELSE NULL END AS customer_rating,
    UNIFORM(0,100,RANDOM()) > 5 AS inventory_available_flag,
    UNIFORM(10, 500, RANDOM()) AS stock_level_at_order,
    rnd_payment < 35 AND UNIFORM(0,100,RANDOM()) < 25 AS high_rto_risk_flag,
    rnd_fraud < 2 AS fraud_flag,
    ARRAY_CONSTRUCT('mobile_app','website','social_media','marketplace')[UNIFORM(0,3,RANDOM())]::STRING AS order_source,
    ARRAY_CONSTRUCT('organic','google_ads','facebook','instagram','email','referral','direct')[UNIFORM(0,6,RANDOM())]::STRING AS traffic_source,
    CASE WHEN UNIFORM(0,100,RANDOM()) < 60 THEN 'CAMP' || LPAD(UNIFORM(1,50,RANDOM())::STRING,3,'0') ELSE NULL END AS campaign_id,
    ROUND(quantity * unit_price * UNIFORM(0.1, 0.4, RANDOM()), 2)::FLOAT AS margin,
    ROUND(quantity * unit_price * UNIFORM(0.05, 0.25, RANDOM()), 2)::FLOAT AS profit
FROM base_data;


select count(*) from orders; --add outliers to showcase fraud detection

SELECT 
    c.customer_id,
    c.first_name,
    c.last_name,
    c.city AS customer_city,
    c.loyalty_tier,
    o.order_id,
    o.order_date,
    o.product_name,
    o.category,
    o.order_value,
    o.payment_type,
    o.order_status
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.customers c
JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.orders o ON c.customer_id = o.customer_id
LIMIT 10;

SELECT 
    c.customer_id,
COUNT(DISTINCT   o.order_iD), SUM(ORDER_VALUE)
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.customers c
JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.orders o ON c.customer_id = o.customer_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

---------------------MARKETING-----------

CREATE OR REPLACE TABLE marketing_interactions (
interaction_id INT,
customer_id INT,
order_id INT,
campaign_id STRING,
campaign_name STRING,
campaign_type STRING,
channel STRING,
message_id STRING,
send_timestamp TIMESTAMP,
delivery_status STRING,
open_flag BOOLEAN,
click_flag BOOLEAN,
conversion_flag BOOLEAN,
conversion_order_id INT,
conversion_value FLOAT,
time_to_open_seconds INT,
time_to_click_seconds INT,
device_type STRING,
platform STRING,
customer_segment STRING,
customer_risk_segment STRING,
personalization_flag BOOLEAN,
recommended_product STRING,
recommended_category STRING,
engagement_score FLOAT,
propensity_to_buy_score FLOAT,
unsubscribe_flag BOOLEAN,
spam_flag BOOLEAN,
fatigue_score FLOAT,
frequency_last_7_days INT,
frequency_last_30_days INT,
best_send_time_hour INT,
ab_test_group STRING,
geo_city STRING,
geo_state STRING,
response_type STRING,
marketing_cost FLOAT,
revenue_generated FLOAT,
roi FLOAT
);

INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.marketing_interactions
WITH base_data AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY SEQ4()) AS interaction_id,
        UNIFORM(1, 3000, RANDOM()) AS customer_id,
        CASE WHEN UNIFORM(0,100,RANDOM()) < 30 THEN UNIFORM(1, 5000, RANDOM()) ELSE NULL END AS order_id,
        'CAMP' || LPAD(UNIFORM(1,50,RANDOM())::STRING,3,'0') AS campaign_id,
        ARRAY_CONSTRUCT('email','whatsapp','sms','push_notification')[UNIFORM(0,3,RANDOM())]::STRING AS channel,
        UNIFORM(0, 100, RANDOM()) AS rnd_delivery,
        UNIFORM(0, 100, RANDOM()) AS rnd_open,
        UNIFORM(0, 100, RANDOM()) AS rnd_click,
        UNIFORM(0, 100, RANDOM()) AS rnd_convert,
        DATEADD(SECOND, -UNIFORM(0, 7776000, RANDOM()), CURRENT_TIMESTAMP()) AS send_timestamp
    FROM TABLE(GENERATOR(ROWCOUNT => 8000))
)
SELECT
    interaction_id,
    customer_id,
    order_id,
    campaign_id,
    ARRAY_CONSTRUCT('Diwali Sale','Summer Clearance','New Arrivals','Flash Sale','Loyalty Rewards','Cart Abandonment','Welcome Series','Re-engagement','Birthday Offer','Festival Special')[UNIFORM(0,9,RANDOM())]::STRING AS campaign_name,
    ARRAY_CONSTRUCT('promotional','transactional','retention','acquisition','reactivation')[UNIFORM(0,4,RANDOM())]::STRING AS campaign_type,
    channel,
    'MSG' || LPAD(interaction_id::STRING, 8, '0') AS message_id,
    send_timestamp,
    CASE WHEN rnd_delivery < 95 THEN 'delivered' WHEN rnd_delivery < 98 THEN 'bounced' ELSE 'failed' END AS delivery_status,
    rnd_delivery < 95 AND rnd_open < 25 AS open_flag,
    rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 AS click_flag,
    rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 AND rnd_convert < 15 AS conversion_flag,
    CASE WHEN rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 AND rnd_convert < 15 THEN UNIFORM(1, 5000, RANDOM()) ELSE NULL END AS conversion_order_id,
    CASE WHEN rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 AND rnd_convert < 15 THEN ROUND(UNIFORM(500.0, 25000.0, RANDOM()), 2)::FLOAT ELSE 0 END AS conversion_value,
    CASE WHEN rnd_delivery < 95 AND rnd_open < 25 THEN UNIFORM(60, 86400, RANDOM()) ELSE NULL END AS time_to_open_seconds,
    CASE WHEN rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 THEN UNIFORM(10, 3600, RANDOM()) ELSE NULL END AS time_to_click_seconds,
    ARRAY_CONSTRUCT('mobile','desktop','tablet')[UNIFORM(0,2,RANDOM())]::STRING AS device_type,
    ARRAY_CONSTRUCT('android','ios','windows','macos','web')[UNIFORM(0,4,RANDOM())]::STRING AS platform,
    ARRAY_CONSTRUCT('high_value','medium_value','low_value','new','dormant','churned')[UNIFORM(0,5,RANDOM())]::STRING AS customer_segment,
    ARRAY_CONSTRUCT('low_risk','medium_risk','high_risk')[UNIFORM(0,2,RANDOM())]::STRING AS customer_risk_segment,
    UNIFORM(0,100,RANDOM()) < 70 AS personalization_flag,
    ARRAY_CONSTRUCT('Wireless Earbuds','Smart Watch','Running Shoes','Cotton T-Shirt','Laptop Stand','Phone Case','Backpack','Water Bottle','Yoga Mat','Bluetooth Speaker')[UNIFORM(0,9,RANDOM())]::STRING AS recommended_product,
    ARRAY_CONSTRUCT('Electronics','Fashion','Home & Kitchen','Beauty','Sports','Books','Grocery','Toys','Health','Automotive')[UNIFORM(0,9,RANDOM())]::STRING AS recommended_category,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS engagement_score,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS propensity_to_buy_score,
    UNIFORM(0,100,RANDOM()) < 2 AS unsubscribe_flag,
    UNIFORM(0,100,RANDOM()) < 1 AS spam_flag,
    ROUND(UNIFORM(0.0, 1.0, RANDOM()), 2)::FLOAT AS fatigue_score,
    UNIFORM(0, 10, RANDOM()) AS frequency_last_7_days,
    UNIFORM(0, 30, RANDOM()) AS frequency_last_30_days,
    UNIFORM(6, 22, RANDOM()) AS best_send_time_hour,
    ARRAY_CONSTRUCT('control','variant_a','variant_b','variant_c')[UNIFORM(0,3,RANDOM())]::STRING AS ab_test_group,
    ARRAY_CONSTRUCT('Mumbai','Delhi','Bangalore','Hyderabad','Chennai','Kolkata','Pune','Ahmedabad','Jaipur','Lucknow')[UNIFORM(0,9,RANDOM())]::STRING AS geo_city,
    ARRAY_CONSTRUCT('Maharashtra','Delhi','Karnataka','Telangana','Tamil Nadu','West Bengal','Gujarat','Rajasthan','Uttar Pradesh','Madhya Pradesh')[UNIFORM(0,9,RANDOM())]::STRING AS geo_state,
    CASE 
        WHEN rnd_delivery >= 95 THEN 'no_delivery'
        WHEN rnd_open >= 25 THEN 'no_open'
        WHEN rnd_click >= 40 THEN 'opened_no_click'
        WHEN rnd_convert >= 15 THEN 'clicked_no_convert'
        ELSE 'converted'
    END AS response_type,
    ROUND(UNIFORM(0.5, 25.0, RANDOM()), 2)::FLOAT AS marketing_cost,
    CASE WHEN rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 AND rnd_convert < 15 THEN ROUND(UNIFORM(500.0, 25000.0, RANDOM()), 2)::FLOAT ELSE 0 END AS revenue_generated,
    CASE WHEN rnd_delivery < 95 AND rnd_open < 25 AND rnd_click < 40 AND rnd_convert < 15 
         THEN ROUND((UNIFORM(500.0, 25000.0, RANDOM()) - UNIFORM(0.5, 25.0, RANDOM())) / UNIFORM(0.5, 25.0, RANDOM()), 2)::FLOAT 
         ELSE -1 END AS roi
FROM base_data;


select top 10 * from SNOWFLAKE_LEARNING_DB.PUBLIC.marketing_interactions;

----------gold table ---------------

CREATE OR REPLACE transient TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.gold_customer_360 AS
WITH order_facts AS (
    SELECT
        customer_id,
        COUNT(*) AS total_orders,
        COUNT(DISTINCT order_id) AS unique_orders,
        SUM(order_value) AS total_order_value,
        SUM(discount_amount) AS total_discount_amount,
        AVG(order_value) AS avg_order_value,
        MAX(order_value) AS max_order_value,
        MIN(order_value) AS min_order_value,
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS last_order_date,
        DATEDIFF(DAY, MIN(order_date), MAX(order_date)) AS order_span_days,
        SUM(quantity) AS total_items_purchased,
        AVG(quantity) AS avg_items_per_order,
        COUNT(DISTINCT category) AS unique_categories_purchased,
        COUNT(DISTINCT brand) AS unique_brands_purchased,
        SUM(CASE WHEN is_returned THEN 1 ELSE 0 END) AS total_returns,
        SUM(CASE WHEN is_cancelled THEN 1 ELSE 0 END) AS total_cancellations,
        SUM(refund_amount) AS total_refund_amount,
        ROUND(SUM(CASE WHEN is_returned THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS return_rate_pct,
        ROUND(SUM(CASE WHEN is_cancelled THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS cancellation_rate_pct,
        SUM(CASE WHEN payment_type = 'COD' THEN 1 ELSE 0 END) AS cod_orders,
        SUM(CASE WHEN payment_type = 'UPI' THEN 1 ELSE 0 END) AS upi_orders,
        SUM(CASE WHEN payment_type = 'Card' THEN 1 ELSE 0 END) AS card_orders,
        SUM(CASE WHEN payment_type = 'Wallet' THEN 1 ELSE 0 END) AS wallet_orders,
        ROUND(SUM(CASE WHEN cod_flag THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS cod_pct,
        SUM(CASE WHEN order_status = 'delivered' THEN 1 ELSE 0 END) AS delivered_orders,
        AVG(delivery_time_days) AS avg_delivery_days,
        AVG(customer_rating) AS avg_customer_rating,
        SUM(CASE WHEN high_rto_risk_flag THEN 1 ELSE 0 END) AS high_rto_risk_orders,
        SUM(CASE WHEN fraud_flag THEN 1 ELSE 0 END) AS fraud_flagged_orders,
        SUM(margin) AS total_margin,
        SUM(profit) AS total_profit,
        MODE(category) AS most_frequent_category,
        MODE(brand) AS most_frequent_brand,
        MODE(payment_type) AS preferred_payment_type,
        MODE(order_source) AS preferred_order_source
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.orders
    GROUP BY customer_id
),
marketing_facts AS (
    SELECT
        customer_id,
        COUNT(*) AS total_marketing_interactions,
        COUNT(DISTINCT campaign_id) AS unique_campaigns_received,
        SUM(CASE WHEN channel = 'email' THEN 1 ELSE 0 END) AS email_interactions,
        SUM(CASE WHEN channel = 'whatsapp' THEN 1 ELSE 0 END) AS whatsapp_interactions,
        SUM(CASE WHEN channel = 'sms' THEN 1 ELSE 0 END) AS sms_interactions,
        SUM(CASE WHEN channel = 'push_notification' THEN 1 ELSE 0 END) AS push_interactions,
        SUM(CASE WHEN delivery_status = 'delivered' THEN 1 ELSE 0 END) AS messages_delivered,
        SUM(CASE WHEN open_flag THEN 1 ELSE 0 END) AS messages_opened,
        SUM(CASE WHEN click_flag THEN 1 ELSE 0 END) AS messages_clicked,
        SUM(CASE WHEN conversion_flag THEN 1 ELSE 0 END) AS messages_converted,
        ROUND(SUM(CASE WHEN open_flag THEN 1 ELSE 0 END) * 100.0 / NULLIF(SUM(CASE WHEN delivery_status = 'delivered' THEN 1 ELSE 0 END), 0), 2) AS open_rate_pct,
        ROUND(SUM(CASE WHEN click_flag THEN 1 ELSE 0 END) * 100.0 / NULLIF(SUM(CASE WHEN open_flag THEN 1 ELSE 0 END), 0), 2) AS click_rate_pct,
        ROUND(SUM(CASE WHEN conversion_flag THEN 1 ELSE 0 END) * 100.0 / NULLIF(SUM(CASE WHEN click_flag THEN 1 ELSE 0 END), 0), 2) AS conversion_rate_pct,
        SUM(conversion_value) AS total_marketing_conversion_value,
        AVG(time_to_open_seconds) AS avg_time_to_open_seconds,
        AVG(time_to_click_seconds) AS avg_time_to_click_seconds,
        AVG(engagement_score) AS avg_engagement_score,
        AVG(propensity_to_buy_score) AS avg_propensity_score,
        SUM(CASE WHEN unsubscribe_flag THEN 1 ELSE 0 END) AS unsubscribe_count,
        SUM(CASE WHEN spam_flag THEN 1 ELSE 0 END) AS spam_flag_count,
        AVG(fatigue_score) AS avg_fatigue_score,
        AVG(frequency_last_7_days) AS avg_freq_last_7_days,
        AVG(frequency_last_30_days) AS avg_freq_last_30_days,
        MODE(best_send_time_hour) AS best_send_time_hour,
        SUM(marketing_cost) AS total_marketing_cost,
        SUM(revenue_generated) AS total_marketing_revenue,
        ROUND(SUM(revenue_generated) / NULLIF(SUM(marketing_cost), 0), 2) AS marketing_roi,
        MODE(channel) AS preferred_channel,
        MODE(device_type) AS preferred_device_marketing,
        MAX(customer_segment) AS latest_customer_segment,
        MAX(customer_risk_segment) AS latest_risk_segment
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.marketing_interactions
    GROUP BY customer_id
)
SELECT
    -- Customer Dimensions
    c.customer_id,
    c.first_name,
    c.last_name,
    c.gender,
    c.date_of_birth,
    c.age,
    c.marital_status,
    c.household_income,
    c.occupation,
    c.education_level,
    c.city,
    c.state,
    c.pincode,
    c.country,
    c.latitude,
    c.longitude,
    c.signup_date,
    c.last_login_date,
    c.customer_tenure_days,
    c.customer_type,
    c.loyalty_tier,
    c.loyalty_points,
    c.preferred_language,
    c.preferred_device,
    c.preferred_payment_method,
    c.avg_session_duration,
    c.sessions_last_30_days,
    c.weekend_shopper_flag,
    c.night_shopper_flag,
    c.preferred_category,
    c.secondary_category,
    c.brand_affinity_score,
    c.email,
    c.phone_number,
    c.whatsapp_opt_in,
    c.email_opt_in,
    c.discount_sensitivity_score,
    c.price_sensitivity_score,
    c.return_behavior_score,
    c.fraud_risk_score,
    c.last_order_date AS profile_last_order_date,
    c.last_order_value AS profile_last_order_value,
    c.customer_lifetime_value AS profile_clv,
    c.total_orders AS profile_total_orders,
    c.referral_source,
    c.campaign_source,
    c.device_os,
    c.app_version,
    c.churn_risk_score,
    c.engagement_score AS profile_engagement_score,
    
    -- Order Facts
    COALESCE(o.total_orders, 0) AS total_orders,
    COALESCE(o.unique_orders, 0) AS unique_orders,
    COALESCE(o.total_order_value, 0) AS total_order_value,
    COALESCE(o.total_discount_amount, 0) AS total_discount_amount,
    o.avg_order_value,
    o.max_order_value,
    o.min_order_value,
    o.first_order_date,
    o.last_order_date,
    o.order_span_days,
    COALESCE(o.total_items_purchased, 0) AS total_items_purchased,
    o.avg_items_per_order,
    COALESCE(o.unique_categories_purchased, 0) AS unique_categories_purchased,
    COALESCE(o.unique_brands_purchased, 0) AS unique_brands_purchased,
    COALESCE(o.total_returns, 0) AS total_returns,
    COALESCE(o.total_cancellations, 0) AS total_cancellations,
    COALESCE(o.total_refund_amount, 0) AS total_refund_amount,
    o.return_rate_pct,
    o.cancellation_rate_pct,
    COALESCE(o.cod_orders, 0) AS cod_orders,
    COALESCE(o.upi_orders, 0) AS upi_orders,
    COALESCE(o.card_orders, 0) AS card_orders,
    COALESCE(o.wallet_orders, 0) AS wallet_orders,
    o.cod_pct,
    COALESCE(o.delivered_orders, 0) AS delivered_orders,
    o.avg_delivery_days,
    o.avg_customer_rating,
    COALESCE(o.high_rto_risk_orders, 0) AS high_rto_risk_orders,
    COALESCE(o.fraud_flagged_orders, 0) AS fraud_flagged_orders,
    COALESCE(o.total_margin, 0) AS total_margin,
    COALESCE(o.total_profit, 0) AS total_profit,
    o.most_frequent_category,
    o.most_frequent_brand,
    o.preferred_payment_type,
    o.preferred_order_source,
    
    -- Marketing Facts
    COALESCE(m.total_marketing_interactions, 0) AS total_marketing_interactions,
    COALESCE(m.unique_campaigns_received, 0) AS unique_campaigns_received,
    COALESCE(m.email_interactions, 0) AS email_interactions,
    COALESCE(m.whatsapp_interactions, 0) AS whatsapp_interactions,
    COALESCE(m.sms_interactions, 0) AS sms_interactions,
    COALESCE(m.push_interactions, 0) AS push_interactions,
    COALESCE(m.messages_delivered, 0) AS messages_delivered,
    COALESCE(m.messages_opened, 0) AS messages_opened,
    COALESCE(m.messages_clicked, 0) AS messages_clicked,
    COALESCE(m.messages_converted, 0) AS messages_converted,
    m.open_rate_pct,
    m.click_rate_pct,
    m.conversion_rate_pct,
    COALESCE(m.total_marketing_conversion_value, 0) AS total_marketing_conversion_value,
    m.avg_time_to_open_seconds,
    m.avg_time_to_click_seconds,
    m.avg_engagement_score,
    m.avg_propensity_score,
    COALESCE(m.unsubscribe_count, 0) AS unsubscribe_count,
    COALESCE(m.spam_flag_count, 0) AS spam_flag_count,
    m.avg_fatigue_score,
    m.avg_freq_last_7_days,
    m.avg_freq_last_30_days,
    m.best_send_time_hour,
    COALESCE(m.total_marketing_cost, 0) AS total_marketing_cost,
    COALESCE(m.total_marketing_revenue, 0) AS total_marketing_revenue,
    m.marketing_roi,
    m.preferred_channel,
    m.preferred_device_marketing,
    m.latest_customer_segment,
    m.latest_risk_segment,
    
    -- Derived Metrics
    COALESCE(o.total_order_value, 0) + COALESCE(m.total_marketing_conversion_value, 0) AS combined_revenue,
    CASE WHEN COALESCE(o.total_orders, 0) > 0 THEN TRUE ELSE FALSE END AS has_ordered,
    CASE WHEN COALESCE(m.total_marketing_interactions, 0) > 0 THEN TRUE ELSE FALSE END AS has_marketing_engagement,
    CURRENT_TIMESTAMP() AS created_at

FROM SNOWFLAKE_LEARNING_DB.PUBLIC.customers c
LEFT JOIN order_facts o ON c.customer_id = o.customer_id
LEFT JOIN marketing_facts m ON c.customer_id = m.customer_id;



select top 10 * from SNOWFLAKE_LEARNING_DB.PUBLIC.gold_customer_360; --3000 rows
