-- CREATE STAGE IF NOT EXISTS SNOWFLAKE_LEARNING_DB.PUBLIC.streamlit_stage;

-- CREATE OR REPLACE STREAMLIT SNOWFLAKE_LEARNING_DB.PUBLIC.ecommerce_explorer
--   ROOT_LOCATION = '@SNOWFLAKE_LEARNING_DB.PUBLIC.streamlit_stage'
--   MAIN_FILE = 'streamlit_app.py'
--   QUERY_WAREHOUSE = COMPUTE_WH;


--   SELECT SNOWFLAKE.CORTEX.COMPLETE('snowflake-arctic', 'say hi') AS test;

--seller--


--CREATE OR REPLACE TRANSIENT TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.FORECAST_CUSTOMER_OUTLOOK AS
WITH customer_data AS (
    SELECT
        c.CUSTOMER_ID,
        c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
        c.CITY,
        c.STATE,
        c.LOYALTY_TIER,
        c.TOTAL_ORDERS,
        c.TOTAL_ORDER_VALUE,
        c.AVG_ORDER_VALUE,
        c.MAX_ORDER_VALUE,
        c.PROFILE_CLV AS CUSTOMER_LIFETIME_VALUE,
        c.CHURN_RISK_SCORE,
        c.PROFILE_ENGAGEMENT_SCORE AS ENGAGEMENT_SCORE,
        c.DISCOUNT_SENSITIVITY_SCORE,
        c.PRICE_SENSITIVITY_SCORE,
        c.RETURN_BEHAVIOR_SCORE,
        c.FRAUD_RISK_SCORE,
        c.LAST_ORDER_DATE,
        c.FIRST_ORDER_DATE,
        c.ORDER_SPAN_DAYS,
        c.TOTAL_RETURNS,
        c.RETURN_RATE_PCT,
        c.UNIQUE_CATEGORIES_PURCHASED,
        c.UNIQUE_BRANDS_PURCHASED,
        c.AVG_ENGAGEMENT_SCORE AS MARKETING_ENGAGEMENT,
        c.AVG_PROPENSITY_SCORE,
        c.OPEN_RATE_PCT,
        c.CLICK_RATE_PCT,
        c.CONVERSION_RATE_PCT,
        c.AVG_FATIGUE_SCORE,
        c.MARKETING_ROI,
        c.PERSONA,
        r.R_SCORE,
        r.F_SCORE,
        r.M_SCORE,
        r.RFM_SCORE,
        r.EXTRACTED_VALUE AS RFM_SEGMENT,
        DATEDIFF(DAY, c.LAST_ORDER_DATE, CURRENT_DATE()) AS DAYS_SINCE_LAST_ORDER,
        CASE WHEN c.ORDER_SPAN_DAYS > 0 THEN c.TOTAL_ORDERS * 30.0 / c.ORDER_SPAN_DAYS ELSE 0 END AS MONTHLY_ORDER_RATE
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMER_AI_360 c
    LEFT JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.RFM_SEGMENTS r ON c.CUSTOMER_ID = r.CUSTOMER_ID
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    PERSONA,

    LOYALTY_TIER AS CURRENT_LOYALTY_TIER,
    CASE
        WHEN LOYALTY_TIER = 'bronze' AND CUSTOMER_LIFETIME_VALUE > 100000 AND ENGAGEMENT_SCORE > 0.6 THEN 'silver'
        WHEN LOYALTY_TIER = 'silver' AND CUSTOMER_LIFETIME_VALUE > 200000 AND ENGAGEMENT_SCORE > 0.7 THEN 'gold'
        WHEN LOYALTY_TIER = 'gold' AND CUSTOMER_LIFETIME_VALUE > 350000 AND ENGAGEMENT_SCORE > 0.8 THEN 'platinum'
        WHEN LOYALTY_TIER = 'platinum' AND CHURN_RISK_SCORE > 0.7 AND ENGAGEMENT_SCORE < 0.3 THEN 'gold'
        WHEN LOYALTY_TIER = 'gold' AND CHURN_RISK_SCORE > 0.7 AND ENGAGEMENT_SCORE < 0.3 THEN 'silver'
        ELSE LOYALTY_TIER
    END AS PREDICTED_LOYALTY_TIER,

    RFM_SEGMENT AS CURRENT_RFM_SEGMENT,
    CASE
        WHEN RFM_SEGMENT = 'Champion' AND DAYS_SINCE_LAST_ORDER > 60 THEN 'At Risk'
        WHEN RFM_SEGMENT = 'Champion' AND DAYS_SINCE_LAST_ORDER > 30 THEN 'Potential Loyalist'
        WHEN RFM_SEGMENT = 'Potential Loyalist' AND MONTHLY_ORDER_RATE >= 3 AND M_SCORE >= 4 THEN 'Champion'
        WHEN RFM_SEGMENT = 'Potential Loyalist' AND DAYS_SINCE_LAST_ORDER > 90 THEN 'At Risk'
        WHEN RFM_SEGMENT = 'New Customer' AND F_SCORE >= 3 AND M_SCORE >= 3 THEN 'Potential Loyalist'
        WHEN RFM_SEGMENT = 'New Customer' AND DAYS_SINCE_LAST_ORDER > 60 THEN 'At Risk'
        WHEN RFM_SEGMENT = 'At Risk' AND DAYS_SINCE_LAST_ORDER > 120 THEN 'At Risk'
        ELSE RFM_SEGMENT
    END AS PREDICTED_RFM_SEGMENT,

    ROUND(CHURN_RISK_SCORE, 3) AS CURRENT_CHURN_RISK,
    CASE
        WHEN CHURN_RISK_SCORE > 0.7 AND DAYS_SINCE_LAST_ORDER > 60 AND ENGAGEMENT_SCORE < 0.3 THEN 'VERY HIGH'
        WHEN CHURN_RISK_SCORE > 0.7 OR (DAYS_SINCE_LAST_ORDER > 45 AND ENGAGEMENT_SCORE < 0.4) THEN 'HIGH'
        WHEN CHURN_RISK_SCORE > 0.4 OR DAYS_SINCE_LAST_ORDER > 30 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS CHURN_PREDICTION_30D,
    ROUND(
        LEAST(1.0, CHURN_RISK_SCORE * 0.4
            + LEAST(1.0, DAYS_SINCE_LAST_ORDER / 120.0) * 0.3
            + (1 - ENGAGEMENT_SCORE) * 0.2
            + (1 - LEAST(1.0, MONTHLY_ORDER_RATE / 5.0)) * 0.1
        ), 3
    ) AS CHURN_PROBABILITY_SCORE,

    ROUND(CUSTOMER_LIFETIME_VALUE, 2) AS CURRENT_CLV,
    ROUND(CUSTOMER_LIFETIME_VALUE + (MONTHLY_ORDER_RATE * AVG_ORDER_VALUE * 3), 2) AS PROJECTED_CLV_90D,
    ROUND(
        CASE WHEN CUSTOMER_LIFETIME_VALUE > 0
            THEN ((MONTHLY_ORDER_RATE * AVG_ORDER_VALUE * 3) / CUSTOMER_LIFETIME_VALUE) * 100
            ELSE 0
        END, 2
    ) AS CLV_GROWTH_PCT_90D,

    ROUND(MONTHLY_ORDER_RATE, 2) AS CURRENT_MONTHLY_ORDER_RATE,
    ROUND(
        CASE
            WHEN DAYS_SINCE_LAST_ORDER > 90 THEN MONTHLY_ORDER_RATE * 0.3
            WHEN DAYS_SINCE_LAST_ORDER > 60 THEN MONTHLY_ORDER_RATE * 0.5
            WHEN DAYS_SINCE_LAST_ORDER > 30 THEN MONTHLY_ORDER_RATE * 0.8
            ELSE MONTHLY_ORDER_RATE
        END, 2
    ) AS PREDICTED_ORDERS_NEXT_30D,

    ROUND(
        (CASE WHEN MAX_ORDER_VALUE > 0 AND AVG_ORDER_VALUE > 0
            THEN (1 - AVG_ORDER_VALUE / MAX_ORDER_VALUE) * 0.4
            ELSE 0 END)
        + (LEAST(1.0, UNIQUE_CATEGORIES_PURCHASED / 10.0) * 0.3)
        + (LEAST(1.0, UNIQUE_BRANDS_PURCHASED / 10.0) * 0.3)
    , 3) AS UPSELL_POTENTIAL_SCORE,

    ROUND(CUSTOMER_LIFETIME_VALUE * LEAST(1.0, CHURN_RISK_SCORE * 0.4
        + LEAST(1.0, DAYS_SINCE_LAST_ORDER / 120.0) * 0.3
        + (1 - ENGAGEMENT_SCORE) * 0.2
        + (1 - LEAST(1.0, MONTHLY_ORDER_RATE / 5.0)) * 0.1
    ), 2) AS REVENUE_AT_RISK,

    CASE
        WHEN CUSTOMER_LIFETIME_VALUE * CHURN_RISK_SCORE > 100000 THEN 'CRITICAL'
        WHEN CHURN_RISK_SCORE > 0.7 AND CUSTOMER_LIFETIME_VALUE > 50000 THEN 'HIGH'
        WHEN CHURN_RISK_SCORE > 0.5 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS RETENTION_PRIORITY,

    CASE
        WHEN ENGAGEMENT_SCORE > 0.7 AND DISCOUNT_SENSITIVITY_SCORE < 0.3 THEN 'STABLE'
        WHEN ENGAGEMENT_SCORE > 0.5 AND DISCOUNT_SENSITIVITY_SCORE < 0.5 THEN 'LIKELY STABLE'
        WHEN CHURN_RISK_SCORE > 0.6 OR ENGAGEMENT_SCORE < 0.3 THEN 'LIKELY SHIFTING'
        ELSE 'MONITOR'
    END AS PERSONA_STABILITY,

    ROUND(
        COALESCE(MARKETING_ENGAGEMENT, 0) * 0.3
        + COALESCE(OPEN_RATE_PCT, 0) / 100.0 * 0.2
        + COALESCE(CLICK_RATE_PCT, 0) / 100.0 * 0.2
        + COALESCE(CONVERSION_RATE_PCT, 0) / 100.0 * 0.2
        + (1 - COALESCE(AVG_FATIGUE_SCORE, 0)) * 0.1
    , 3) AS MARKETING_RESPONSIVENESS_SCORE,

    CASE
        WHEN RETENTION_PRIORITY = 'CRITICAL' THEN 'IMMEDIATE_WINBACK_CAMPAIGN'
        WHEN CHURN_PREDICTION_30D = 'VERY HIGH' THEN 'PERSONALIZED_RETENTION_OFFER'
        WHEN CHURN_PREDICTION_30D = 'HIGH' THEN 'LOYALTY_BONUS_ACTIVATION'
        WHEN UPSELL_POTENTIAL_SCORE > 0.6 THEN 'UPSELL_CROSS_SELL_CAMPAIGN'
        WHEN PERSONA_STABILITY = 'LIKELY SHIFTING' THEN 'ENGAGEMENT_REACTIVATION'
        WHEN PREDICTED_RFM_SEGMENT != CURRENT_RFM_SEGMENT THEN 'SEGMENT_TRANSITION_NURTURE'
        ELSE 'STANDARD_ENGAGEMENT'
    END AS RECOMMENDED_INTERVENTION,

    CURRENT_TIMESTAMP() AS FORECAST_GENERATED_AT

FROM customer_data;



SELECT * FROM SNOWFLAKE_LEARNING_DB.PUBLIC.FORECAST_CUSTOMER_OUTLOOK LIMIT 10;

