CREATE OR REPLACE PROCEDURE SNOWFLAKE_LEARNING_DB.PUBLIC.SP_REFRESH_ANALYTICS_PIPELINE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    v_sql VARCHAR;
    v_start TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP();
BEGIN
    SELECT QUERY_TEXT INTO v_sql
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE QUERY_ID = '01c316bb-0001-adb0-000c-ce0a00012436';
    EXECUTE IMMEDIATE v_sql;

    SELECT QUERY_TEXT INTO v_sql
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE QUERY_ID = '01c31c1e-0001-adad-000c-ce0a0005e0ce';
    EXECUTE IMMEDIATE v_sql;

    SELECT QUERY_TEXT INTO v_sql
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE QUERY_ID = '01c3271e-0001-b045-000c-ce0a00111d12';
    EXECUTE IMMEDIATE v_sql;

    SELECT QUERY_TEXT INTO v_sql
    FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
    WHERE QUERY_ID = '01c3271e-0001-b045-000c-ce0a00111d0e';
    EXECUTE IMMEDIATE v_sql;

    RETURN 'Pipeline refreshed: GOLD_CUSTOMER_360, GOLD_SELLER_360, FORECAST_CUSTOMER_OUTLOOK, FORECAST_SELLER_OUTLOOK rebuilt at ' || CURRENT_TIMESTAMP()::VARCHAR || ' (took ' || DATEDIFF(SECOND, v_start, CURRENT_TIMESTAMP()) || 's)';
END;
$$
;

CREATE OR REPLACE STREAM SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_REALTIME_FOR_MERGE
    ON TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
    APPEND_ONLY = TRUE; 

CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_REALTIME_FOR_MERGE')
AS
    CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE();

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES RESUME;

SELECT COUNT(*) AS ORDERS_BEFORE FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS; --current

CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE(); -- manual run


SELECT COUNT(*) AS MAPPING_COUNT FROM SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMER_SELLER_MAPPING --check updated

SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, CATEGORY, ORDER_VALUE, PAYMENT_TYPE, ORDER_STATUS, SHIPPING_CITY, MARGIN, PROFIT
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS WHERE ORDER_ID > 5000 ORDER BY ORDER_ID DESC LIMIT 5; --check new orders

SELECT COUNT(*) AS ORDERS_AFTER FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS --verify

-- Events → Stream → Process → REALTIME_ORDER_EVENTS
--                                  ├→ Dynamic Tables (real-time forecasts)
--                                  └→ ORDERS base table + CUSTOMER_SELLER_MAPPING (via merge task)


-- TASK_GENERATE_EVENTS (1 min)
--   → REALTIME_ORDER_EVENTS
--     → STREAM → TASK_PROCESS_ON_STREAM_DATA (consumes stream)
--     → STREAM → TASK_MERGE_TO_BASE_TABLES (merges into ORDERS)
--       → STREAM on ORDERS → TASK_REFRESH_ANALYTICS (rebuilds gold + forecasts)
--         → GOLD_CUSTOMER_360 ✅ (now shows orders up to 2026-03-23)
--         → GOLD_SELLER_360 ✅
--         → FORECAST_CUSTOMER_OUTLOOK ✅ (refreshed at 15:16:32)
--         → FORECAST_SELLER_OUTLOOK ✅ (refreshed at 15:16:35)
--           → DT_ overlay tables auto-cascade

