-- ================================================================
-- REAL-TIME FORECASTING PIPELINE
-- ================================================================
-- Architecture:
--   [Task: every 1 min] → SP_GENERATE_TEST_EVENTS
--       → REALTIME_ORDER_EVENTS (landing table)
--           → STREAM_ORDER_EVENTS (CDC)
--               → DT_CUSTOMER_RECENT_ACTIVITY (Layer 1, DOWNSTREAM)
--               → DT_SELLER_RECENT_ACTIVITY   (Layer 1, DOWNSTREAM)
--                   → DT_FORECAST_CUSTOMER_OUTLOOK (Layer 2, 5 min lag)
--                   → DT_FORECAST_SELLER_OUTLOOK   (Layer 2, 5 min lag)
-- ================================================================


-- ============================================================
-- STEP 1: EVENTS LANDING TABLE
-- ============================================================

CREATE OR REPLACE TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS (
    EVENT_ID NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    EVENT_TIMESTAMP TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CUSTOMER_ID NUMBER,
    SELLER_ID NUMBER,
    ORDER_VALUE FLOAT,
    CATEGORY VARCHAR,
    PAYMENT_TYPE VARCHAR,
    IS_RETURNED BOOLEAN DEFAULT FALSE,
    IS_CANCELLED BOOLEAN DEFAULT FALSE,
    CUSTOMER_RATING NUMBER,
    DELIVERY_TIME_DAYS NUMBER
);


-- ============================================================
-- STEP 2: STREAM ON EVENTS TABLE (CDC)
-- ============================================================

CREATE OR REPLACE STREAM SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS
    ON TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
    APPEND_ONLY = TRUE;


-- ============================================================
-- STEP 3: STORED PROCEDURE - GENERATE TEST EVENTS
-- ============================================================

CREATE OR REPLACE PROCEDURE SNOWFLAKE_LEARNING_DB.PUBLIC.SP_GENERATE_TEST_EVENTS(NUM_EVENTS INT)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    cnt INT;
BEGIN
    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
        (CUSTOMER_ID, SELLER_ID, ORDER_VALUE, CATEGORY, PAYMENT_TYPE,
         IS_RETURNED, IS_CANCELLED, CUSTOMER_RATING, DELIVERY_TIME_DAYS)
    SELECT
        c.CUSTOMER_ID,
        s.SELLER_ID,
        ROUND(UNIFORM(200::FLOAT, 8000::FLOAT, RANDOM()), 2),
        c.PREFERRED_CATEGORY,
        c.PREFERRED_PAYMENT_METHOD,
        IFF(UNIFORM(0, 100, RANDOM()) < 12, TRUE, FALSE),
        IFF(UNIFORM(0, 100, RANDOM()) < 6, TRUE, FALSE),
        UNIFORM(1, 5, RANDOM()),
        UNIFORM(1, 10, RANDOM())
    FROM
        (SELECT CUSTOMER_ID, PREFERRED_CATEGORY, PREFERRED_PAYMENT_METHOD
         FROM SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMERS
         ORDER BY RANDOM()
         LIMIT :NUM_EVENTS) c
    CROSS JOIN
        (SELECT SELLER_ID
         FROM SNOWFLAKE_LEARNING_DB.PUBLIC.SELLERS
         ORDER BY RANDOM()
         LIMIT 1) s;

    cnt := SQLROWCOUNT;
    RETURN 'Generated ' || cnt::VARCHAR || ' events at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;


-- ============================================================
-- STEP 4: SCHEDULED TASK - AUTO-GENERATE EVENTS EVERY MINUTE
-- ============================================================

CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_GENERATE_EVENTS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
AS
    CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_GENERATE_TEST_EVENTS(10);


-- ============================================================
-- STEP 4B: TRIGGERED TASK - AUTO-PROCESS WHEN STREAM HAS DATA
-- ============================================================
-- This task has NO schedule — it checks every minute if the stream
-- has new data, and ONLY fires when SYSTEM$STREAM_HAS_DATA is TRUE.

CREATE OR REPLACE PROCEDURE SNOWFLAKE_LEARNING_DB.PUBLIC.SP_PROCESS_STREAM_EVENTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    row_count INT;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE _stream_batch AS
    SELECT * FROM SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS;

    SELECT COUNT(*) INTO :row_count FROM _stream_batch;

    IF (row_count > 0) THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
            (CUSTOMER_ID, SELLER_ID, ORDER_VALUE, CATEGORY, PAYMENT_TYPE,
             IS_RETURNED, IS_CANCELLED, CUSTOMER_RATING, DELIVERY_TIME_DAYS)
        SELECT CUSTOMER_ID, SELLER_ID, ORDER_VALUE, CATEGORY, PAYMENT_TYPE,
               IS_RETURNED, IS_CANCELLED, CUSTOMER_RATING, DELIVERY_TIME_DAYS
        FROM _stream_batch;
    END IF;

    RETURN 'Processed ' || row_count::VARCHAR || ' stream events at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;

CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS')
AS
    CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_PROCESS_STREAM_EVENTS();

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA RESUME;


-- ============================================================
-- STEP 5: DYNAMIC TABLES - LAYER 1 (RECENT ACTIVITY AGGREGATION)
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.DT_CUSTOMER_RECENT_ACTIVITY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
AS
SELECT
    CUSTOMER_ID,
    COUNT(*) AS RECENT_ORDER_COUNT,
    ROUND(SUM(ORDER_VALUE), 2) AS RECENT_ORDER_VALUE,
    ROUND(AVG(ORDER_VALUE), 2) AS RECENT_AVG_ORDER_VALUE,
    MAX(EVENT_TIMESTAMP) AS LAST_EVENT_TIME,
    SUM(IFF(IS_RETURNED, 1, 0)) AS RECENT_RETURNS,
    SUM(IFF(IS_CANCELLED, 1, 0)) AS RECENT_CANCELLATIONS,
    ROUND(AVG(CUSTOMER_RATING), 2) AS RECENT_AVG_RATING,
    ROUND(AVG(DELIVERY_TIME_DAYS), 1) AS RECENT_AVG_DELIVERY_DAYS,
    ROUND(SUM(IFF(IS_RETURNED, 1, 0))::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS RECENT_RETURN_RATE
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
GROUP BY CUSTOMER_ID;


CREATE OR REPLACE DYNAMIC TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.DT_SELLER_RECENT_ACTIVITY
    TARGET_LAG = DOWNSTREAM
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
AS
SELECT
    SELLER_ID,
    COUNT(*) AS RECENT_ORDER_COUNT,
    ROUND(SUM(ORDER_VALUE), 2) AS RECENT_ORDER_VALUE,
    ROUND(AVG(ORDER_VALUE), 2) AS RECENT_AVG_ORDER_VALUE,
    COUNT(DISTINCT CUSTOMER_ID) AS RECENT_UNIQUE_CUSTOMERS,
    MAX(EVENT_TIMESTAMP) AS LAST_EVENT_TIME,
    SUM(IFF(IS_RETURNED, 1, 0)) AS RECENT_RETURNS,
    SUM(IFF(IS_CANCELLED, 1, 0)) AS RECENT_CANCELLATIONS,
    ROUND(AVG(CUSTOMER_RATING), 2) AS RECENT_AVG_RATING,
    ROUND(AVG(DELIVERY_TIME_DAYS), 1) AS RECENT_AVG_DELIVERY_DAYS,
    ROUND(SUM(IFF(IS_RETURNED, 1, 0))::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS RECENT_RETURN_RATE
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
GROUP BY SELLER_ID;


-- ============================================================
-- STEP 6: DYNAMIC TABLES - LAYER 2 (REAL-TIME FORECAST OVERLAY)
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.DT_FORECAST_CUSTOMER_OUTLOOK
    TARGET_LAG = '5 minutes'
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
AS
SELECT
    f.CUSTOMER_ID,
    f.CUSTOMER_NAME,
    f.CITY,
    f.STATE,
    f.PERSONA,
    f.CURRENT_LOYALTY_TIER,
    f.PREDICTED_LOYALTY_TIER,
    f.CURRENT_RFM_SEGMENT,
    f.PREDICTED_RFM_SEGMENT,

    f.CURRENT_CHURN_RISK,
    f.CHURN_PREDICTION_30D AS BASELINE_CHURN_PREDICTION,
    f.CHURN_PROBABILITY_SCORE AS BASELINE_CHURN_SCORE,

    COALESCE(ra.RECENT_ORDER_COUNT, 0) AS REALTIME_ORDER_COUNT,
    COALESCE(ra.RECENT_ORDER_VALUE, 0) AS REALTIME_ORDER_VALUE,
    ra.LAST_EVENT_TIME AS LAST_REALTIME_EVENT,

    ROUND(GREATEST(0,
        f.CHURN_PROBABILITY_SCORE
        - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
        - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -6, CURRENT_TIMESTAMP()), 0.10, 0)
        - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP()), 0.05, 0)
    ), 3) AS REALTIME_CHURN_SCORE,

    CASE
        WHEN GREATEST(0,
            f.CHURN_PROBABILITY_SCORE
            - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
            - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -6, CURRENT_TIMESTAMP()), 0.10, 0)
            - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -1, CURRENT_TIMESTAMP()), 0.05, 0)
        ) > 0.7 THEN 'VERY HIGH'
        WHEN GREATEST(0,
            f.CHURN_PROBABILITY_SCORE
            - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
            - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -6, CURRENT_TIMESTAMP()), 0.10, 0)
        ) > 0.5 THEN 'HIGH'
        WHEN GREATEST(0,
            f.CHURN_PROBABILITY_SCORE
            - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
        ) > 0.3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS REALTIME_CHURN_PREDICTION,

    ROUND(f.CURRENT_CLV + COALESCE(ra.RECENT_ORDER_VALUE, 0), 2) AS REALTIME_CLV,
    f.CURRENT_CLV AS BASELINE_CLV,

    ROUND(f.PROJECTED_CLV_90D + COALESCE(ra.RECENT_ORDER_VALUE, 0) * 3, 2) AS REALTIME_PROJECTED_CLV_90D,
    f.PROJECTED_CLV_90D AS BASELINE_PROJECTED_CLV_90D,

    ROUND(
        (f.CURRENT_CLV + COALESCE(ra.RECENT_ORDER_VALUE, 0))
        * GREATEST(0,
            f.CHURN_PROBABILITY_SCORE
            - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
            - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -6, CURRENT_TIMESTAMP()), 0.10, 0)
        ), 2
    ) AS REALTIME_REVENUE_AT_RISK,
    f.REVENUE_AT_RISK AS BASELINE_REVENUE_AT_RISK,

    CASE
        WHEN (f.CURRENT_CLV + COALESCE(ra.RECENT_ORDER_VALUE, 0))
             * GREATEST(0, f.CHURN_PROBABILITY_SCORE - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03) > 100000
            THEN 'CRITICAL'
        WHEN GREATEST(0, f.CHURN_PROBABILITY_SCORE - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03) > 0.7
             AND (f.CURRENT_CLV + COALESCE(ra.RECENT_ORDER_VALUE, 0)) > 50000
            THEN 'HIGH'
        WHEN GREATEST(0, f.CHURN_PROBABILITY_SCORE - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03) > 0.5
            THEN 'MEDIUM'
        ELSE 'LOW'
    END AS REALTIME_RETENTION_PRIORITY,
    f.RETENTION_PRIORITY AS BASELINE_RETENTION_PRIORITY,

    IFF(f.CHURN_PREDICTION_30D != CASE
        WHEN GREATEST(0, f.CHURN_PROBABILITY_SCORE - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
            - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -6, CURRENT_TIMESTAMP()), 0.10, 0)) > 0.7 THEN 'VERY HIGH'
        WHEN GREATEST(0, f.CHURN_PROBABILITY_SCORE - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03
            - IFF(ra.LAST_EVENT_TIME >= DATEADD(HOUR, -6, CURRENT_TIMESTAMP()), 0.10, 0)) > 0.5 THEN 'HIGH'
        WHEN GREATEST(0, f.CHURN_PROBABILITY_SCORE - COALESCE(ra.RECENT_ORDER_COUNT, 0) * 0.03) > 0.3 THEN 'MEDIUM'
        ELSE 'LOW'
    END, TRUE, FALSE) AS PREDICTION_CHANGED,

    f.UPSELL_POTENTIAL_SCORE,
    f.PERSONA_STABILITY,
    f.MARKETING_RESPONSIVENESS_SCORE,
    f.RECOMMENDED_INTERVENTION,
    CURRENT_TIMESTAMP() AS LAST_REFRESHED_AT

FROM SNOWFLAKE_LEARNING_DB.PUBLIC.FORECAST_CUSTOMER_OUTLOOK f
LEFT JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.DT_CUSTOMER_RECENT_ACTIVITY ra
    ON f.CUSTOMER_ID = ra.CUSTOMER_ID;


CREATE OR REPLACE DYNAMIC TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.DT_FORECAST_SELLER_OUTLOOK
    TARGET_LAG = '5 minutes'
    WAREHOUSE = COMPUTE_WH
    REFRESH_MODE = FULL
    INITIALIZE = ON_CREATE
AS
SELECT
    f.SELLER_ID,
    f.SELLER_NAME,
    f.SELLER_TYPE,
    f.SELLER_CATEGORY,
    f.SELLER_CITY,
    f.YEARS_ON_PLATFORM,
    f.CURRENT_SELLER_TIER,
    f.PREDICTED_SELLER_TIER,

    f.CURRENT_REVENUE AS BASELINE_REVENUE,
    ROUND(f.CURRENT_REVENUE + COALESCE(ra.RECENT_ORDER_VALUE, 0), 2) AS REALTIME_REVENUE,
    COALESCE(ra.RECENT_ORDER_COUNT, 0) AS REALTIME_ORDER_COUNT,
    COALESCE(ra.RECENT_ORDER_VALUE, 0) AS REALTIME_ORDER_VALUE,
    COALESCE(ra.RECENT_UNIQUE_CUSTOMERS, 0) AS REALTIME_NEW_CUSTOMERS,
    ra.LAST_EVENT_TIME AS LAST_REALTIME_EVENT,

    ROUND(
        CASE WHEN f.CURRENT_REVENUE > 0
            THEN (COALESCE(ra.RECENT_ORDER_VALUE, 0) / f.CURRENT_REVENUE) * 100
            ELSE 0
        END, 2
    ) AS REALTIME_REVENUE_LIFT_PCT,

    f.PROJECTED_REVENUE_90D AS BASELINE_PROJECTED_REV_90D,
    ROUND(f.PROJECTED_REVENUE_90D + COALESCE(ra.RECENT_ORDER_VALUE, 0) * 12, 2) AS REALTIME_PROJECTED_REV_90D,

    f.REVENUE_GROWTH_TREND,

    f.CURRENT_RISK_SEGMENT,
    f.RISK_FORECAST AS BASELINE_RISK_FORECAST,
    f.RISK_ESCALATION_PROBABILITY AS BASELINE_RISK_PROB,

    ROUND(GREATEST(0,
        f.RISK_ESCALATION_PROBABILITY
        + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3
        - IFF(COALESCE(ra.RECENT_AVG_RATING, 0) >= 4, 0.05, 0)
        - IFF(COALESCE(ra.RECENT_ORDER_COUNT, 0) >= 5, 0.03, 0)
    ), 3) AS REALTIME_RISK_SCORE,

    CASE
        WHEN GREATEST(0, f.RISK_ESCALATION_PROBABILITY
            + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3
            - IFF(COALESCE(ra.RECENT_AVG_RATING, 0) >= 4, 0.05, 0)) > 0.7 THEN 'CRITICAL'
        WHEN GREATEST(0, f.RISK_ESCALATION_PROBABILITY
            + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3) > 0.5 THEN 'HIGH'
        WHEN GREATEST(0, f.RISK_ESCALATION_PROBABILITY
            + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3) > 0.3 THEN 'ELEVATED'
        ELSE 'STABLE'
    END AS REALTIME_RISK_FORECAST,

    f.OPERATIONAL_HEALTH_SCORE AS BASELINE_OPS_HEALTH,
    ROUND(GREATEST(0, LEAST(100,
        f.OPERATIONAL_HEALTH_SCORE
        - COALESCE(ra.RECENT_RETURN_RATE, 0) * 0.5
        + IFF(COALESCE(ra.RECENT_AVG_DELIVERY_DAYS, 99) <= 3, 5, 0)
        + IFF(COALESCE(ra.RECENT_AVG_RATING, 0) >= 4, 3, 0)
    )), 2) AS REALTIME_OPS_HEALTH,

    f.SUSTAINABILITY_SCORE AS BASELINE_SUSTAINABILITY,

    f.REVENUE_AT_RISK AS BASELINE_REVENUE_AT_RISK,
    ROUND(
        (f.CURRENT_REVENUE + COALESCE(ra.RECENT_ORDER_VALUE, 0))
        * GREATEST(0,
            f.RISK_ESCALATION_PROBABILITY
            + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3
            - IFF(COALESCE(ra.RECENT_AVG_RATING, 0) >= 4, 0.05, 0)
        ), 2
    ) AS REALTIME_REVENUE_AT_RISK,

    f.PROFIT_TRAJECTORY,
    f.CUSTOMER_BASE_TREND,
    f.INVESTMENT_RECOMMENDATION,
    f.RECOMMENDED_ACTION,

    IFF(f.RISK_FORECAST != CASE
        WHEN GREATEST(0, f.RISK_ESCALATION_PROBABILITY + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3
            - IFF(COALESCE(ra.RECENT_AVG_RATING, 0) >= 4, 0.05, 0)) > 0.7 THEN 'CRITICAL'
        WHEN GREATEST(0, f.RISK_ESCALATION_PROBABILITY + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3) > 0.5 THEN 'HIGH'
        WHEN GREATEST(0, f.RISK_ESCALATION_PROBABILITY + COALESCE(ra.RECENT_RETURN_RATE, 0) / 100.0 * 0.3) > 0.3 THEN 'ELEVATED'
        ELSE 'STABLE'
    END, TRUE, FALSE) AS PREDICTION_CHANGED,

    CURRENT_TIMESTAMP() AS LAST_REFRESHED_AT

FROM SNOWFLAKE_LEARNING_DB.PUBLIC.FORECAST_SELLER_OUTLOOK f
LEFT JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.DT_SELLER_RECENT_ACTIVITY ra
    ON f.SELLER_ID = ra.SELLER_ID;

--------------------------------------------------this is premade but stream is suspended-------------
-- ============================================================
-- STEP 7: RESUME THE TASK (start generating events)
-- ============================================================


SELECT COUNT(*) FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS;
-- Result: 0 (or whatever existed before). Sets the baseline.

CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_GENERATE_TEST_EVENTS(10);--Manually inject events

SELECT * FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
ORDER BY EVENT_TIMESTAMP DESC LIMIT 10; --test data present

-- Check stream has data
SELECT SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS') AS has_new_data;

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_GENERATE_EVENTS RESUME;

SELECT COUNT(*) AS TOTAL_EVENTS,
       MIN(EVENT_TIMESTAMP) AS FIRST_EVENT,
       MAX(EVENT_TIMESTAMP) AS LAST_EVENT
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS;


-- ============================================================
-- STEP 8: MANUAL TEST - Generate events immediately
-- ============================================================

CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_GENERATE_TEST_EVENTS(10);


-- ============================================================
-- MONITORING QUERIES
-- ============================================================

-- Check events flowing in
SELECT COUNT(*) AS total_events,
       MIN(EVENT_TIMESTAMP) AS first_event,
       MAX(EVENT_TIMESTAMP) AS last_event
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS;

-- View real-time customer forecast with changes highlighted
SELECT CUSTOMER_ID, CUSTOMER_NAME,
       BASELINE_CHURN_PREDICTION, REALTIME_CHURN_PREDICTION,
       BASELINE_CLV, REALTIME_CLV,
       REALTIME_ORDER_COUNT, REALTIME_ORDER_VALUE,
       PREDICTION_CHANGED, LAST_REFRESHED_AT
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.DT_FORECAST_CUSTOMER_OUTLOOK
WHERE PREDICTION_CHANGED = TRUE
ORDER BY REALTIME_ORDER_VALUE DESC
LIMIT 20;

-- View real-time seller forecast with changes highlighted
SELECT SELLER_ID, SELLER_NAME,
       BASELINE_RISK_FORECAST, REALTIME_RISK_FORECAST,
       BASELINE_REVENUE, REALTIME_REVENUE,
       REALTIME_ORDER_COUNT, REALTIME_ORDER_VALUE, REALTIME_REVENUE_LIFT_PCT,
       PREDICTION_CHANGED, LAST_REFRESHED_AT
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.DT_FORECAST_SELLER_OUTLOOK
WHERE PREDICTION_CHANGED = TRUE
ORDER BY REALTIME_ORDER_VALUE DESC
LIMIT 20;

-- Task execution history
SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'TASK_GENERATE_EVENTS',
    RESULT_LIMIT => 10
))
ORDER BY SCHEDULED_TIME DESC;

-- To stop the pipeline:
-- ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_GENERATE_EVENTS SUSPEND;



SELECT
    s.seller_id,
    s.seller_name,
    s.seller_tier,
    s.seller_category,
    s.seller_type,
    s.total_revenue,
    s.total_orders,
    s.avg_order_value,
    s.seller_score,
    s.avg_customer_rating,
    s.return_rate_pct,
    s.cancellation_rate_pct,
    s.fraud_flag_rate
FROM
    SNOWFLAKE_LEARNING_DB.PUBLIC.SELLERS s
WHERE
    s.seller_id IN ('Seller_144', 'Seller_152', 'Seller_174', 'Seller_189', 'Seller_20', 'Seller_36', 'Seller_55')
LIMIT 20;



--verify
SHOW TASKS LIKE 'TASK_PROCESS_ON_STREAM_DATA' IN SCHEMA SNOWFLAKE_LEARNING_DB.PUBLIC;


ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_GENERATE_EVENTS SUSPEND;
ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA SUSPEND;