--check if new data present
SELECT SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS') AS HAS_NEW_DATA;

SELECT COUNT(*) AS TOTAL_EVENTS, MIN(EVENT_TIMESTAMP) AS FIRST_EVENT, MAX(EVENT_TIMESTAMP) AS LAST_EVENT FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS; --new events

SHOW TASKS IN SCHEMA SNOWFLAKE_LEARNING_DB.PUBLIC; --see all tasks

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_GENERATE_EVENTS RESUME; --resume event generation
ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA RESUME;

SELECT COUNT(*) AS TOTAL, SUM(CASE WHEN PREDICTION_CHANGED THEN 1 ELSE 0 END) AS PREDICTIONS_CHANGED FROM SNOWFLAKE_LEARNING_DB.PUBLIC.DT_FORECAST_SELLER_OUTLOOK; --seller forecast new data check

SELECT NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, ERROR_MESSAGE
FROM TABLE(SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(RESULT_LIMIT => 15))
ORDER BY SCHEDULED_TIME DESC; --task execution history

SELECT COUNT(*) AS ROWss, MAX(RECENT_ORDER_VALUE) AS MAX_ORDER_VAL FROM SNOWFLAKE_LEARNING_DB.PUBLIC.DT_CUSTOMER_RECENT_ACTIVITY; --customer recent activity

SELECT COUNT(*) AS ROWSs, MAX(RECENT_ORDER_VALUE) AS MAX_ORDER_VAL FROM SNOWFLAKE_LEARNING_DB.PUBLIC.DT_SELLER_RECENT_ACTIVITY; --seller recent activity

SELECT COUNT(*) AS TOTAL, SUM(CASE WHEN PREDICTION_CHANGED THEN 1 ELSE 0 END) AS PREDICTIONS_CHANGED FROM SNOWFLAKE_LEARNING_DB.PUBLIC.DT_FORECAST_CUSTOMER_OUTLOOK; --customer forecast



Component	Status	Details
TASK_GENERATE_EVENTS	RUNNING	Resumed, generating 10 events/min
TASK_PROCESS_ON_STREAM_DATA	RUNNING	4 recent executions, all SUCCEEDED
STREAM_ORDER_EVENTS	ACTIVE	Has data = TRUE, being consumed
REALTIME_ORDER_EVENTS	320 events	First: 12:04 → Latest: 14:38
DT_CUSTOMER_RECENT_ACTIVITY (L1)	40 customers	Max order value: ₹76,944
DT_SELLER_RECENT_ACTIVITY (L1)	4 sellers	Max order value: ₹4,60,940
DT_FORECAST_CUSTOMER_OUTLOOK (L2)	3,000 customers	1,197 predictions changed (40%)
DT_FORECAST_SELLER_OUTLOOK (L2)	200 sellers	169 predictions changed (85%)
Everything is flowing: Task → Events → Stream → Dynamic Tables → Forecast Updates.

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_GENERATE_EVENTS SUSPEND;
ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA SUSPEND;



-- TASK_GENERATE_EVENTS (1 min)
--     → REALTIME_ORDER_EVENTS (landing table)
--         → STREAM_ORDER_EVENTS (CDC)
--             → TASK_PROCESS_ON_STREAM_DATA (consumes stream)
--                 → DT_CUSTOMER_RECENT_ACTIVITY (Layer 1, auto)
--                 → DT_SELLER_RECENT_ACTIVITY (Layer 1, auto)
--                     → DT_FORECAST_CUSTOMER_OUTLOOK (Layer 2, 5-min refresh) ← forecasts here
--                     → DT_FORECAST_SELLER_OUTLOOK (Layer 2, 5-min refresh)   ← forecasts here