CREATE OR REPLACE PROCEDURE SNOWFLAKE_LEARNING_DB.PUBLIC.SP_PROCESS_STREAM_EVENTS()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    row_count INT;
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE _stream_batch AS
    SELECT * FROM SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS;

    SELECT COUNT(*) INTO :row_count FROM _stream_batch;

    IF (row_count > 0) THEN
        INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
            (CUSTOMER_ID, SELLER_ID, ORDER_VALUE, CATEGORY, PAYMENT_TYPE,
             IS_RETURNED, IS_CANCELLED, CUSTOMER_RATING, DELIVERY_TIME_DAYS)
        SELECT CUSTOMER_ID, SELLER_ID, ORDER_VALUE, CATEGORY, PAYMENT_TYPE,
               IS_RETURNED, IS_CANCELLED, CUSTOMER_RATING, DELIVERY_TIME_DAYS
        FROM _stream_batch;
    END IF;

    RETURN 'Processed ' || row_count::VARCHAR || ' stream events at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$

CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_ORDER_EVENTS')
    AS
    CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_PROCESS_STREAM_EVENTS();

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_PROCESS_ON_STREAM_DATA RESUME;