CREATE OR REPLACE PROCEDURE SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    max_order_id INT;
    new_max_order_id INT;
BEGIN
    SELECT COALESCE(MAX(ORDER_ID), 0) INTO :max_order_id FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS;

    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS (
        ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_TIME, PRODUCT_ID, PRODUCT_NAME,
        BRAND, CATEGORY, SUB_CATEGORY, QUANTITY, UNIT_PRICE, ORDER_VALUE,
        DISCOUNT_AMOUNT, COUPON_CODE, PAYMENT_TYPE, PAYMENT_STATUS, ORDER_STATUS,
        DELIVERY_PARTNER, WAREHOUSE_ID, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_PINCODE,
        DELIVERY_TIME_DAYS, IS_RETURNED, RETURN_REASON, REFUND_AMOUNT,
        IS_CANCELLED, CANCELLATION_REASON, COD_FLAG, CUSTOMER_RATING,
        INVENTORY_AVAILABLE_FLAG, STOCK_LEVEL_AT_ORDER, HIGH_RTO_RISK_FLAG,
        FRAUD_FLAG, ORDER_SOURCE, TRAFFIC_SOURCE, CAMPAIGN_ID, MARGIN, PROFIT
    )
    SELECT
        :max_order_id + ROW_NUMBER() OVER (ORDER BY EVENT_TIMESTAMP),
        r.CUSTOMER_ID,
        r.EVENT_TIMESTAMP::DATE,
        TO_CHAR(r.EVENT_TIMESTAMP, 'HH24:MI:SS'),
        'P' || (ABS(HASH(r.EVENT_ID)) % 500 + 1),
        'Product_' || (ABS(HASH(r.EVENT_ID)) % 500 + 1),
        CASE ABS(HASH(r.EVENT_ID || 'brand')) % 5
            WHEN 0 THEN 'BrandA' WHEN 1 THEN 'BrandB' WHEN 2 THEN 'BrandC'
            WHEN 3 THEN 'BrandD' ELSE 'BrandE' END,
        r.CATEGORY,
        r.CATEGORY || '_sub',
        GREATEST(1, ABS(HASH(r.EVENT_ID || 'qty')) % 5),
        ROUND(r.ORDER_VALUE / GREATEST(1, ABS(HASH(r.EVENT_ID || 'qty')) % 5), 2),
        r.ORDER_VALUE,
        ROUND(r.ORDER_VALUE * (ABS(HASH(r.EVENT_ID || 'disc')) % 20) / 100.0, 2),
        CASE WHEN ABS(HASH(r.EVENT_ID || 'coupon')) % 3 = 0 THEN 'COUP' || (ABS(HASH(r.EVENT_ID)) % 100) ELSE NULL END,
        r.PAYMENT_TYPE,
        CASE WHEN r.IS_CANCELLED THEN 'Refunded' ELSE 'Completed' END,
        CASE WHEN r.IS_CANCELLED THEN 'Cancelled'
             WHEN r.IS_RETURNED THEN 'Returned'
             ELSE 'Delivered' END,
        CASE ABS(HASH(r.EVENT_ID || 'dp')) % 4
            WHEN 0 THEN 'Delhivery' WHEN 1 THEN 'BlueDart'
            WHEN 2 THEN 'Ecom Express' ELSE 'DTDC' END,
        'WH' || (ABS(HASH(r.EVENT_ID || 'wh')) % 10 + 1),
        c.CITY,
        c.STATE,
        c.PINCODE,
        r.DELIVERY_TIME_DAYS,
        r.IS_RETURNED,
        CASE WHEN r.IS_RETURNED THEN
            CASE ABS(HASH(r.EVENT_ID || 'rr')) % 4
                WHEN 0 THEN 'Defective' WHEN 1 THEN 'Wrong item'
                WHEN 2 THEN 'Not as described' ELSE 'Changed mind' END
            ELSE NULL END,
        CASE WHEN r.IS_RETURNED THEN ROUND(r.ORDER_VALUE * 0.9, 2) ELSE 0 END,
        r.IS_CANCELLED,
        CASE WHEN r.IS_CANCELLED THEN
            CASE ABS(HASH(r.EVENT_ID || 'cr')) % 3
                WHEN 0 THEN 'Customer request' WHEN 1 THEN 'Out of stock' ELSE 'Payment failed' END
            ELSE NULL END,
        CASE WHEN r.PAYMENT_TYPE = 'COD' THEN TRUE ELSE FALSE END,
        r.CUSTOMER_RATING,
        TRUE,
        ABS(HASH(r.EVENT_ID || 'stk')) % 500 + 10,
        CASE WHEN r.IS_RETURNED AND r.DELIVERY_TIME_DAYS > 5 THEN TRUE ELSE FALSE END,
        CASE WHEN r.ORDER_VALUE > 15000 AND r.PAYMENT_TYPE = 'COD' THEN TRUE ELSE FALSE END,
        CASE ABS(HASH(r.EVENT_ID || 'src')) % 3 WHEN 0 THEN 'app' WHEN 1 THEN 'web' ELSE 'mobile' END,
        CASE ABS(HASH(r.EVENT_ID || 'trf')) % 4 WHEN 0 THEN 'organic' WHEN 1 THEN 'paid' WHEN 2 THEN 'social' ELSE 'direct' END,
        CASE WHEN ABS(HASH(r.EVENT_ID || 'cmp')) % 3 = 0 THEN 'CMP' || (ABS(HASH(r.EVENT_ID)) % 50) ELSE NULL END,
        ROUND(r.ORDER_VALUE * (15 + ABS(HASH(r.EVENT_ID || 'mgn')) % 20) / 100.0, 2),
        ROUND(r.ORDER_VALUE * (5 + ABS(HASH(r.EVENT_ID || 'pft')) % 15) / 100.0, 2)
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS r
    JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMERS c ON r.CUSTOMER_ID = c.CUSTOMER_ID
    WHERE r.EVENT_ID NOT IN (
        SELECT EVENT_ID FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED
    );

    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED
    SELECT EVENT_ID FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
    WHERE EVENT_ID NOT IN (SELECT EVENT_ID FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED);

    SELECT COALESCE(MAX(ORDER_ID), 0) INTO :new_max_order_id FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS;

    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMER_SELLER_MAPPING (CUSTOMER_ID, ORDER_ID, PRODUCT_ID, CATEGORY, SELLER_ID)
    SELECT
        o.CUSTOMER_ID,
        o.ORDER_ID,
        o.PRODUCT_ID,
        o.CATEGORY,
        r.SELLER_ID
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS o
    JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS r
        ON o.CUSTOMER_ID = r.CUSTOMER_ID
        AND o.ORDER_DATE = r.EVENT_TIMESTAMP::DATE
        AND o.ORDER_VALUE = r.ORDER_VALUE
    WHERE o.ORDER_ID > :max_order_id;

    RETURN 'Merged orders ' || (:max_order_id + 1)::VARCHAR || ' to ' || :new_max_order_id::VARCHAR || ' into base ORDERS table';
END;
$$
;


CREATE TABLE IF NOT EXISTS SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED (EVENT_ID NUMBER);

CREATE OR REPLACE STREAM SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_REALTIME_FOR_MERGE
    ON TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_REALTIME_FOR_MERGE')
AS
    CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE();


ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES RESUME;

--manual test
SELECT COUNT(*) AS ORDERS_BEFORE FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS;

CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE(); --new updates

SELECT COUNT(*) AS MAPPING_COUNT FROM SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMER_SELLER_MAPPING;

SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, CATEGORY, ORDER_VALUE, PAYMENT_TYPE, ORDER_STATUS, SHIPPING_CITY, MARGIN, PROFIT
FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS WHERE ORDER_ID > 5000 ORDER BY ORDER_ID DESC LIMIT 5;

SELECT COUNT(*) AS ORDERS_AFTER FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS; --verify after merge

-- ============================================================
-- STEP 4C: AUTO-MERGE REALTIME EVENTS INTO BASE ORDERS TABLE
-- ============================================================
-- Tracks which events have been merged, maps 11 realtime columns
-- to all 39 ORDERS columns, and updates CUSTOMER_SELLER_MAPPING.

CREATE TABLE IF NOT EXISTS SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED (EVENT_ID NUMBER);

CREATE OR REPLACE STREAM SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_REALTIME_FOR_MERGE
    ON TABLE SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
    APPEND_ONLY = TRUE;

CREATE OR REPLACE PROCEDURE SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE()
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
DECLARE
    max_order_id INT;
    new_max_order_id INT;
BEGIN
    SELECT COALESCE(MAX(ORDER_ID), 0) INTO :max_order_id FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS;

    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS (
        ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_TIME, PRODUCT_ID, PRODUCT_NAME,
        BRAND, CATEGORY, SUB_CATEGORY, QUANTITY, UNIT_PRICE, ORDER_VALUE,
        DISCOUNT_AMOUNT, COUPON_CODE, PAYMENT_TYPE, PAYMENT_STATUS, ORDER_STATUS,
        DELIVERY_PARTNER, WAREHOUSE_ID, SHIPPING_CITY, SHIPPING_STATE, SHIPPING_PINCODE,
        DELIVERY_TIME_DAYS, IS_RETURNED, RETURN_REASON, REFUND_AMOUNT,
        IS_CANCELLED, CANCELLATION_REASON, COD_FLAG, CUSTOMER_RATING,
        INVENTORY_AVAILABLE_FLAG, STOCK_LEVEL_AT_ORDER, HIGH_RTO_RISK_FLAG,
        FRAUD_FLAG, ORDER_SOURCE, TRAFFIC_SOURCE, CAMPAIGN_ID, MARGIN, PROFIT
    )
    SELECT
        :max_order_id + ROW_NUMBER() OVER (ORDER BY EVENT_TIMESTAMP),
        r.CUSTOMER_ID,
        r.EVENT_TIMESTAMP::DATE,
        TO_CHAR(r.EVENT_TIMESTAMP, 'HH24:MI:SS'),
        'P' || (ABS(HASH(r.EVENT_ID)) % 500 + 1),
        'Product_' || (ABS(HASH(r.EVENT_ID)) % 500 + 1),
        CASE ABS(HASH(r.EVENT_ID || 'brand')) % 5
            WHEN 0 THEN 'BrandA' WHEN 1 THEN 'BrandB' WHEN 2 THEN 'BrandC'
            WHEN 3 THEN 'BrandD' ELSE 'BrandE' END,
        r.CATEGORY,
        r.CATEGORY || '_sub',
        GREATEST(1, ABS(HASH(r.EVENT_ID || 'qty')) % 5),
        ROUND(r.ORDER_VALUE / GREATEST(1, ABS(HASH(r.EVENT_ID || 'qty')) % 5), 2),
        r.ORDER_VALUE,
        ROUND(r.ORDER_VALUE * (ABS(HASH(r.EVENT_ID || 'disc')) % 20) / 100.0, 2),
        CASE WHEN ABS(HASH(r.EVENT_ID || 'coupon')) % 3 = 0 THEN 'COUP' || (ABS(HASH(r.EVENT_ID)) % 100) ELSE NULL END,
        r.PAYMENT_TYPE,
        CASE WHEN r.IS_CANCELLED THEN 'Refunded' ELSE 'Completed' END,
        CASE WHEN r.IS_CANCELLED THEN 'Cancelled'
             WHEN r.IS_RETURNED THEN 'Returned'
             ELSE 'Delivered' END,
        CASE ABS(HASH(r.EVENT_ID || 'dp')) % 4
            WHEN 0 THEN 'Delhivery' WHEN 1 THEN 'BlueDart'
            WHEN 2 THEN 'Ecom Express' ELSE 'DTDC' END,
        'WH' || (ABS(HASH(r.EVENT_ID || 'wh')) % 10 + 1),
        c.CITY,
        c.STATE,
        c.PINCODE,
        r.DELIVERY_TIME_DAYS,
        r.IS_RETURNED,
        CASE WHEN r.IS_RETURNED THEN
            CASE ABS(HASH(r.EVENT_ID || 'rr')) % 4
                WHEN 0 THEN 'Defective' WHEN 1 THEN 'Wrong item'
                WHEN 2 THEN 'Not as described' ELSE 'Changed mind' END
            ELSE NULL END,
        CASE WHEN r.IS_RETURNED THEN ROUND(r.ORDER_VALUE * 0.9, 2) ELSE 0 END,
        r.IS_CANCELLED,
        CASE WHEN r.IS_CANCELLED THEN
            CASE ABS(HASH(r.EVENT_ID || 'cr')) % 3
                WHEN 0 THEN 'Customer request' WHEN 1 THEN 'Out of stock' ELSE 'Payment failed' END
            ELSE NULL END,
        CASE WHEN r.PAYMENT_TYPE = 'COD' THEN TRUE ELSE FALSE END,
        r.CUSTOMER_RATING,
        TRUE,
        ABS(HASH(r.EVENT_ID || 'stk')) % 500 + 10,
        CASE WHEN r.IS_RETURNED AND r.DELIVERY_TIME_DAYS > 5 THEN TRUE ELSE FALSE END,
        CASE WHEN r.ORDER_VALUE > 15000 AND r.PAYMENT_TYPE = 'COD' THEN TRUE ELSE FALSE END,
        CASE ABS(HASH(r.EVENT_ID || 'src')) % 3 WHEN 0 THEN 'app' WHEN 1 THEN 'web' ELSE 'mobile' END,
        CASE ABS(HASH(r.EVENT_ID || 'trf')) % 4 WHEN 0 THEN 'organic' WHEN 1 THEN 'paid' WHEN 2 THEN 'social' ELSE 'direct' END,
        CASE WHEN ABS(HASH(r.EVENT_ID || 'cmp')) % 3 = 0 THEN 'CMP' || (ABS(HASH(r.EVENT_ID)) % 50) ELSE NULL END,
        ROUND(r.ORDER_VALUE * (15 + ABS(HASH(r.EVENT_ID || 'mgn')) % 20) / 100.0, 2),
        ROUND(r.ORDER_VALUE * (5 + ABS(HASH(r.EVENT_ID || 'pft')) % 15) / 100.0, 2)
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS r
    JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMERS c ON r.CUSTOMER_ID = c.CUSTOMER_ID
    WHERE r.EVENT_ID NOT IN (
        SELECT EVENT_ID FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED
    );

    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED
    SELECT EVENT_ID FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS
    WHERE EVENT_ID NOT IN (SELECT EVENT_ID FROM SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_EVENTS_MERGED);

    SELECT COALESCE(MAX(ORDER_ID), 0) INTO :new_max_order_id FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS;

    INSERT INTO SNOWFLAKE_LEARNING_DB.PUBLIC.CUSTOMER_SELLER_MAPPING (CUSTOMER_ID, ORDER_ID, PRODUCT_ID, CATEGORY, SELLER_ID)
    SELECT
        o.CUSTOMER_ID,
        o.ORDER_ID,
        o.PRODUCT_ID,
        o.CATEGORY,
        r.SELLER_ID
    FROM SNOWFLAKE_LEARNING_DB.PUBLIC.ORDERS o
    JOIN SNOWFLAKE_LEARNING_DB.PUBLIC.REALTIME_ORDER_EVENTS r
        ON o.CUSTOMER_ID = r.CUSTOMER_ID
        AND o.ORDER_DATE = r.EVENT_TIMESTAMP::DATE
        AND o.ORDER_VALUE = r.ORDER_VALUE
    WHERE o.ORDER_ID > :max_order_id;

    RETURN 'Merged orders ' || (:max_order_id + 1)::VARCHAR || ' to ' || :new_max_order_id::VARCHAR || ' into base ORDERS table';
END;
$$;

CREATE OR REPLACE TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA('SNOWFLAKE_LEARNING_DB.PUBLIC.STREAM_REALTIME_FOR_MERGE')
AS
    CALL SNOWFLAKE_LEARNING_DB.PUBLIC.SP_MERGE_REALTIME_TO_BASE();

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES RESUME;

ALTER TASK SNOWFLAKE_LEARNING_DB.PUBLIC.TASK_MERGE_TO_BASE_TABLES suspend;


-- Events → Stream → Process → REALTIME_ORDER_EVENTS
--                                  ├→ Dynamic Tables (real-time forecasts)
--                                  └→ ORDERS base table + CUSTOMER_SELLER_MAPPING (via merge task)


